apiVersion: apps/v1
kind: Deployment
metadata:
  name: aik8s-api
  namespace: aik8s-demo
  labels:
    app: aik8s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aik8s-api
  template:
    metadata:
      labels:
        app: aik8s-api
    spec:
      containers:
      - name: aik8s-api-container
        image: acrscll.azurecr.io/aik8s-api:v5
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: app-env-secret  # Matches your secret name
              key: appinsights-connection-string  # matches the key of the secret data
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aik8s-api
  namespace: aik8s-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aik8s-api  